---
- name: Adding user
  hosts: all
  tasks:

    - rabbitmq_user: 
        user: Shrikesh
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present     
