- name: Adding user
  hosts: all
  tasks:

    - rabbitmq_user:
        user: Amrith
        password: test
        #configure_priv: .*
        #read_priv: .*
        #write_priv: .*
        #tags: administrator
        state: absent

