---
- hosts: nfs-server
  remote_user: ansible
  become: yes

  tasks:
    - name: install firewalld
      yum: name=firewalld state=latest

    - name: enable firewalld
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - firewalld
    - name: Start  firewalld Service
      shell: systemctl start firewalld


 # -name: install firewalld
 #   yum: name=firewalld state=installed


  #  - name: Enable firewalld on system reboot
  #    service: name=firewalld enabled=yes


  # - name: Start service firewalld, if not started
   #  service:
    #   name: firewalld
     #  state: started
