---
- hosts: nfs-server
  remote_user: ansible
  become: yes
  
  tasks:
    - name: install nfs-utils
      yum: name=nfs-utils state=latest

    - name: Create a mountable Directory 
      file:
        path: /home/shared
        state: directory
        owner: ansible
        group: ansible
        mode: '0775'
 


    - name: enable rpcbind nfslock nfs
      service:
        name: "{{ item }}"
        enabled: yes
      with_items:
        - rpcbind
        - nfslock
        - nfs

    - name: Copy exports file
      template:
       src: /home/NFS-TASK/exports.j2
       dest: /etc/exports
       owner: ansible
       group: ansible
       mode: 0644
    - name: NFS apply change configure
      shell: systemctl reload nfs;exportfs -a
