---
  - name: PostgreSQL
    hosts: target1
    become: yes
    vars:
    vars_prompt:
        - name: create_user
          prompt: Enter the value of createuser
          private: no

    gather_facts: false
    tasks:

      - block:
          - name: Install repository
            yum:
              name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
              state: present

          - name: enable the module stream for Postgres version 12
            command: sudo dnf module enable postgresql:12

          - name: Install PostgreSQ 12
            command: sudo dnf install postgresql-server

          - name: Install PostgreSQL Contribute
            command: sudo yum install -y  postgresql-contrib

          - name: Create a new PostgreSQL database cluster with initdb
            command: sudo /usr/pgsql-12/bin/postgresql-12-setup initdb
            register: test_out
          - debug: var=test_out

          - name: Start PostgreSQL services
            command: sudo systemctl start postgresql

          - name: enable PostgreSQL services
            command: sudo systemctl enable postgresql

          - name: To check the status of PostgreSQL services
            command: systemctl status postgresql-12.service
            register: test_out1
          - debug: var=test_out1

          - name: pip install postgres devel
            command: sudo yum install python3-devel

          - name: pip install postgres libs
            command: sudo yum groupinstall 'development tools'

          - name: pip install psycopg2 for postgres
            command: sudo pip3 install psycopg2==2.7.5 --ignore-installed

          - name: installing the ansible postgres modeule
            command: ansible-galaxy collection install community.postgresql

        ignore_errors: yes
