[osboxes@nsiblecontroller ~]$ ansible-galaxy install openstack-ansible-galaxy.rabbitmq
- downloading role 'rabbitmq', owned by openstack-ansible-galaxy
- downloading role from https://github.com/openstack-ansible-galaxy/rabbitmq/archive/master.tar.gz
- extracting openstack-ansible-galaxy.rabbitmq to /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq
- openstack-ansible-galaxy.rabbitmq (master) was installed successfully

[osboxes@nsiblecontroller ~]$ su
Password:

[root@nsiblecontroller osboxes]# cd /home/osboxes/.ansible/roles
[root@nsiblecontroller roles]# ls
openstack-ansible-galaxy.rabbitmq

[root@nsiblecontroller roles]# cat inventory.txt
target1 ansible_host=192.168.1.23 ansible_ssh_pass=osboxes.org

[root@nsiblecontroller roles]# ssh 192.168.1.23
The authenticity of host '192.168.1.23 (192.168.1.23)' can't be established.
ECDSA key fingerprint is SHA256:WEZri0ei2WOBa7FAv9jrH/OoDjMR/7ahh9990DOpE88.
ECDSA key fingerprint is MD5:d4:17:c2:68:c8:49:f0:a5:b7:6b:ef:ac:e2:d7:59:6e.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.23' (ECDSA) to the list of known hosts.
root@192.168.1.23's password:
Last login: Wed Mar  3 02:48:43 2021 from nsiblecontroller.dlink

[root@osboxes ~]# exit
logout
Connection to 192.168.1.23 closed.

[root@nsiblecontroller roles]# vi playbook.yml

[root@nsiblecontroller roles]# ansible-playbook -i inventory.txt playbook.yml

PLAY [all] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
included: /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq/tasks/packages_redhat.yml for target1

TASK [openstack-ansible-galaxy.rabbitmq : Install OpenStack centos-release-openstack-ocata release package] **************************************************
skipping: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : Install rabbitmq-server] *******************************************************************************************
changed: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
skipping: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
included: /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq/tasks/configuration.yml for target1

TASK [openstack-ansible-galaxy.rabbitmq : Configure RabbitMQ] ************************************************************************************************
changed: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : RabbitMQ Environment-specific configuration] ***********************************************************************
skipping: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : RabbitMQ set Erlang cookie] ****************************************************************************************
skipping: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : Set up max file-descriptor limits in RabbitMQ systemd service] *****************************************************
skipping: [target1]

RUNNING HANDLER [openstack-ansible-galaxy.rabbitmq : Reload systemd services and restart RabbitMQ] ***********************************************************
changed: [target1]

RUNNING HANDLER [openstack-ansible-galaxy.rabbitmq : Restart RabbitMQ server] ********************************************************************************
changed: [target1]

RUNNING HANDLER [openstack-ansible-galaxy.rabbitmq : Force stop node so it can join the cluster] *************************************************************
skipping: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
included: /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq/tasks/plugins.yml for target1

TASK [openstack-ansible-galaxy.rabbitmq : Enable rabbitmq plugins] *******************************************************************************************
skipping: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
included: /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq/tasks/vhost.yml for target1

TASK [openstack-ansible-galaxy.rabbitmq : Add RabbitMQ vhosts] ***********************************************************************************************

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
included: /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq/tasks/user.yml for target1

TASK [openstack-ansible-galaxy.rabbitmq : Manage RabbitMQ users and privileges] ******************************************************************************

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
included: /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq/tasks/policy.yml for target1

TASK [openstack-ansible-galaxy.rabbitmq : Manage RabbitMQ policies] ******************************************************************************************

TASK [openstack-ansible-galaxy.rabbitmq : include_tasks] *****************************************************************************************************
included: /home/osboxes/.ansible/roles/openstack-ansible-galaxy.rabbitmq/tasks/sanitycheck.yml for target1

TASK [openstack-ansible-galaxy.rabbitmq : Check RabbitMQ status] *********************************************************************************************
ok: [target1]

TASK [openstack-ansible-galaxy.rabbitmq : Debug RabbitMQ status] *********************************************************************************************
ok: [target1] => {
    "rabbitmqctl_status": {
        "changed": false,
        "cmd": [
            "rabbitmqctl",
            "status"
        ],
        "delta": "0:00:00.666292",
        "end": "2021-03-03 07:24:09.203134",
        "failed": false,
        "rc": 0,
        "start": "2021-03-03 07:24:08.536842",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "Status of node rabbit@osboxes ...\n[{pid,3803},\n {running_applications,[{rabbit,\"RabbitMQ\",\"3.3.5\"},\n                        {os_mon,\"CPO  CXC 138 46\",\"2.2.14\"},\n                        {mnesia,\"MNESIA  CXC 138 12\",\"4.11\"},\n                        {xmerl,\"XML parser\",\"1.3.6\"},\n                        {sasl,\"SASL  CXC 138 11\",\"2.3.4\"},\n                        {stdlib,\"ERTS  CXC 138 10\",\"1.19.4\"},\n                        {kernel,\"ERTS  CXC 138 10\",\"2.16.4\"}]},\n {os,{unix,linux}},\n {erlang_version,\"Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:30] [hipe] [kernel-poll:true]\\n\"},\n {memory,[{total,35857296},\n          {connection_procs,2800},\n          {queue_procs,5600},\n          {plugins,0},\n          {other_proc,13602904},\n          {mnesia,60208},\n          {mgmt_db,0},\n          {msg_index,22136},\n          {other_ets,761712},\n          {binary,17456},\n          {code,16702314},\n          {atom,602729},\n          {other_system,4079437}]},\n {alarms,[]},\n {listeners,[{clustering,25672,\"::\"},{amqp,5672,\"::\"}]},\n {vm_memory_high_watermark,0.4},\n {vm_memory_limit,771152281},\n {disk_free_limit,50000000},\n {disk_free,215341830144},\n {file_descriptors,[{total_limit,924},\n                    {total_used,3},\n                    {sockets_limit,829},\n                    {sockets_used,1}]},\n {processes,[{limit,1048576},{used,125}]},\n {run_queue,0},\n {uptime,7}]\n...done.",
        "stdout_lines": [
            "Status of node rabbit@osboxes ...",
            "[{pid,3803},",
            " {running_applications,[{rabbit,\"RabbitMQ\",\"3.3.5\"},",
            "                        {os_mon,\"CPO  CXC 138 46\",\"2.2.14\"},",
            "                        {mnesia,\"MNESIA  CXC 138 12\",\"4.11\"},",
            "                        {xmerl,\"XML parser\",\"1.3.6\"},",
            "                        {sasl,\"SASL  CXC 138 11\",\"2.3.4\"},",
            "                        {stdlib,\"ERTS  CXC 138 10\",\"1.19.4\"},",
            "                        {kernel,\"ERTS  CXC 138 10\",\"2.16.4\"}]},",
            " {os,{unix,linux}},",
            " {erlang_version,\"Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:30] [hipe] [kernel-poll:true]\\n\"},",
            " {memory,[{total,35857296},",
            "          {connection_procs,2800},",
            "          {queue_procs,5600},",
            "          {plugins,0},",
            "          {other_proc,13602904},",
            "          {mnesia,60208},",
            "          {mgmt_db,0},",
            "          {msg_index,22136},",
            "          {other_ets,761712},",
            "          {binary,17456},",
            "          {code,16702314},",
            "          {atom,602729},",
            "          {other_system,4079437}]},",
            " {alarms,[]},",
            " {listeners,[{clustering,25672,\"::\"},{amqp,5672,\"::\"}]},",
            " {vm_memory_high_watermark,0.4},",
            " {vm_memory_limit,771152281},",
            " {disk_free_limit,50000000},",
            " {disk_free,215341830144},",
            " {file_descriptors,[{total_limit,924},",
            "                    {total_used,3},",
            "                    {sockets_limit,829},",
            "                    {sockets_used,1}]},",
            " {processes,[{limit,1048576},{used,125}]},",
            " {run_queue,0},",
            " {uptime,7}]",
            "...done."
        ]
    }
}

PLAY RECAP ***************************************************************************************************************************************************
target1                    : ok=14   changed=4    unreachable=0    failed=0    skipped=10   rescued=0    ignored=0

[root@nsiblecontroller roles]#

